version: '3.8'

services:
  go:
    container_name: go-service
    working_dir: /app
    build: .
    env_file:
      - ./.env
    environment:
      - MONGO_URI=$URI
    ports:
      - "$PORT:$PORT"
    depends_on:
        - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$PASSWORD
    ports:
      - '27017:27017'