import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "A Lo Junior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/img/favicon.ico" sizes="any" />
      <body className={inter.className}>
        <Header />
        <div className="container mx-auto px-4 mt-24">
          {children}
        </div>
      </body>
    </html>
  );
}
